# Generated by Django 3.2 on 2022-08-16 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_coupon'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name_plural': 'Shop information'},
        ),
    ]
