# Generated by Django 3.2 on 2022-08-20 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_sub_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='num_of_sales',
            field=models.IntegerField(default=0),
        ),
    ]
