# Generated by Django 3.2 on 2022-08-26 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='comment',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
