# Generated by Django 3.2 on 2022-08-26 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_discount_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discount',
            old_name='end',
            new_name='discount_end',
        ),
        migrations.RenameField(
            model_name='discount',
            old_name='start',
            new_name='discount_start',
        ),
    ]
