# Generated by Django 3.2 on 2022-08-26 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20220826_1458'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pill',
            old_name='cart',
            new_name='cartitem',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='status',
            field=models.CharField(choices=[('done', 'done'), ('waiting', 'waiting')], default='waiting', max_length=50),
        ),
        migrations.AddField(
            model_name='pill',
            name='status',
            field=models.CharField(choices=[('done', 'done'), ('waiting', 'waiting')], default='waiting', max_length=50),
        ),
    ]
