# Generated by Django 3.2 on 2022-08-26 13:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0012_auto_20220826_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='pill',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='pill',
            name='cartitem',
        ),
        migrations.AddField(
            model_name='pill',
            name='cartitem',
            field=models.ManyToManyField(to='products.CartItem'),
        ),
    ]
