# Generated by Django 3.2 on 2022-08-27 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_auto_20220827_0044'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.color'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='size',
            field=models.CharField(choices=[('s', 's'), ('xs', 'xs'), ('m', 'm'), ('l', 'l'), ('xl', 'xl'), ('xxl', 'xxl'), ('xxxl', 'xxxl')], default='s', max_length=50),
        ),
    ]
