# Generated by Django 3.2 on 2022-08-29 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_coupondiscount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shuipping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='pill',
            name='cartitem',
            field=models.ManyToManyField(blank=True, null=True, to='products.CartItem'),
        ),
    ]
