# Generated by Django 3.2 on 2022-08-29 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_shipping_shipping_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupondiscount',
            name='coupon',
            field=models.CharField(blank=True, editable=False, max_length=100, null=True),
        ),
    ]
