# Generated by Django 3.2 on 2022-08-29 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_auto_20220829_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='pill',
            name='date_added',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='status',
            field=models.CharField(choices=[('done', 'done'), ('waiting', 'waiting'), ('pilled', 'pilled')], default='waiting', max_length=50),
        ),
    ]
