# Generated by Django 3.2 on 2022-09-01 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_auto_20220829_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='pill',
            name='pill_coupon_discount',
            field=models.FloatField(default=0.0),
        ),
    ]
