# Generated by Django 3.2 on 2022-09-02 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_auto_20220902_2326'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='date_added',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
