# Generated by Django 3.2 on 2022-09-02 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_rating_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='date_added',
            field=models.DateField(auto_now_add=True, default='2020-03-04'),
            preserve_default=False,
        ),
    ]
