# Generated by Django 3.2 on 2022-09-02 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0026_alter_rating_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='date_added',
            field=models.DateField(auto_now=True),
        ),
    ]
