# Generated by Django 3.2 on 2022-08-23 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20220822_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useradditionalinfo',
            name='image',
            field=models.ImageField(default='/static/img/avatar.jpeg', null=True, upload_to='userimages/'),
        ),
    ]
